package org.lichee.simple.example.entity;

// Generated 2012-8-13 14:18:57 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "se_role")
public class SeRole implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private String roleDesc;
	private Date roleCreateTime;
	private Date roleUpadteTime;
	private Set<SeRolePermission> rolePermissions = new HashSet<SeRolePermission>(0);
	private Set<SeUserRole> userRoles = new HashSet<SeUserRole>(0);

	public SeRole() {
	}
	
	public SeRole(Integer roleId, String roleName, String roleDesc,
			Date roleCreateTime, Date roleUpadteTime) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.roleCreateTime = roleCreateTime;
		this.roleUpadteTime = roleUpadteTime;
	}

	public SeRole(Integer roleId, String roleName, String roleDesc,
			Date roleCreateTime, Date roleUpadteTime,
			Set<SeRolePermission> rolePermissions, Set<SeUserRole> userRoles) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.roleCreateTime = roleCreateTime;
		this.roleUpadteTime = roleUpadteTime;
		this.rolePermissions = rolePermissions;
		this.userRoles = userRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", nullable = false, length = 60)
	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc", nullable = false, length = 65535)
	public String getRoleDesc() {
		return roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "role_create_time", nullable = false, length = 19)
	public Date getRoleCreateTime() {
		return roleCreateTime;
	}

	public void setRoleCreateTime(Date roleCreateTime) {
		this.roleCreateTime = roleCreateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "role_upadte_time", length = 19)
	public Date getRoleUpadteTime() {
		return roleUpadteTime;
	}

	public void setRoleUpadteTime(Date roleUpadteTime) {
		this.roleUpadteTime = roleUpadteTime;
	}

	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL}, mappedBy = "role")
	@JsonIgnore
	public Set<SeRolePermission> getRolePermissions() {
		return rolePermissions;
	}

	public void setRolePermissions(Set<SeRolePermission> rolePermissions) {
		this.rolePermissions = rolePermissions;
	}

	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL}, mappedBy = "role")
	@JsonIgnore
	public Set<SeUserRole> getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(Set<SeUserRole> userRoles) {
		this.userRoles = userRoles;
	}

	

}
