package org.lichee.simple.example.entity;

// Generated 2013-7-10 17:02:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "task")
public class Task implements java.io.Serializable {

	private Integer taskId;
	private String taskName;
	private String taskDesc;

	// private TestClass testClass;

	public Task() {
	}

	public Task(Integer taskId, String taskName, String taskDesc) {
		this.taskId = taskId;
		this.taskName = taskName;
		this.taskDesc = taskDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "task_id", unique = true, nullable = false)
	public Integer getTaskId() {
		return taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "task_name", nullable = false, length = 20)
	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "task_desc", nullable = false, length = 200)
	public String getTaskDesc() {
		return taskDesc;
	}

	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}
	
	// @ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.MERGE})
	// @JoinColumn(name = "test_class", nullable = false)
	// public TestClass getTestClass() {
	// return this.testClass;
	// }
	// public void setTestClass(TestClass testClass) {
	// this.testClass = testClass;
	// }

}
