package org.lichee.simple.example.entity;

// Generated 2013-7-10 17:02:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test")
public class Test implements java.io.Serializable {

	private Integer testId;
	// private TestClass testClass;
	private String testName;
	private String testDesc;

	public Test() {
	}

	public Test(Integer testId, String testName, String testDesc) {
		this.testId = testId;
		this.testName = testName;
		this.testDesc = testDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "test_id", unique = true, nullable = false)
	public Integer getTestId() {
		return this.testId;
	}

	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	// @ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.MERGE})
	// @JoinColumn(name = "test_class", nullable = false)
	// public TestClass getTestClass() {
	// return this.testClass;
	// }
	// public void setTestClass(TestClass testClass) {
	// this.testClass = testClass;
	// }

	@Column(name = "test_name", nullable = false, length = 20)
	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	@Column(name = "test_desc", nullable = false, length = 200)
	public String getTestDesc() {
		return testDesc;
	}

	public void setTestDesc(String testDesc) {
		this.testDesc = testDesc;
	}

}
